In [ ]:
#simple function for calculating circle radius 
import math

def area (radius):
    area =math.pi * radius**2
    return(area)
area(10)

In [ ]:
# Data Structures in Python: List, Tuple, Dictionary, Set
# function that compute meaan of a set of 3 numbers

def mean(a,b,c):
    mean = (a+b+c)/3
    return(mean)
mean(5,10,15)

#But what if I need a function that can compute a mean from a set of any given size, say N?

def meanX(numbers):
    meanX = sum(numbers)/len(numbers)
    return(meanX)
meanX([1,3,5]) #as A list 2. meanX([5,10,15,20,25,150])

#List of strings
str_list = ["Belgrade", "New Zeland", "Paris"] # belgrade = 0 , new zeland = 1 paris = 2
str_list[0] 

str = "LukaJasovicGenius"
str[0:3] #"Luk"
str[-3:] #Last 3 letters 

#function to create a list 
#empty_list = list()
#empty_list.append(5)
#empty_list.append(5)
##empty_list.append(10)
#print(empty_list)

#list extension
list1 = ["Mark","Peter"]
list2 = ["Wendy", "Becky"]
list1.extend(list2)
print(list1)

# Checking if something is in the list! Using "in"
"Mark" in list1 #True in this case, because Mark is ineed in the list
if "Mark" in list1:
    print("Yes, Mark is in the list1")

#Counting the elements in the list
my_number_list = [1,2,3,4,5,6,6,7,3,4,7,8,9,10]
my_number_list.count(5) 

#Tuple vs List
list = [1,2,3]
type(list) 
tuple = (1,2,3)
type(tuple) 
# converting one into another
tuple = type(list)
print(tuple) # converted into the list

In [ ]:
#Dictonaries - Key : Value , starting with curly bracket. "{"
my_dict = {
    "key-1": 45,
    "key-2": 50,
    "key-3": 75
    }

my_dict["key-1"] # output will be value attached to the key , in this case it's 45

new_list = [['Paris', 2165423], ['New York', 8804190], ['Belgrade', 1166763]]



#Check if a particular key is present in a dictionary:

city_population = {'Belgrade':1166763, 
                   'Paris': 2165423, 
                   'New York': 8804190}
'Belgrade' in city_population

#Check the value of the key using .get():

city_population.get('Belgrade') 

#list all keys
city_population.keys()

In [ ]:
# .copy() = The .copy() method is used in Python to create a shallow copy of a list, dictionary, or other objects like DataFrames in pandas. 
# A shallow copy means that it creates a new object but does not create copies of the objects inside it. Instead, it references the same objects in memory.

original_list = [1,2,3,4]

a = [1,2,3,4,5]
b=a
b.append(10)
print(a)
print(b)
# So, a = b and b = a in Python mean only that a and b refer to the same object. If you want to assign a to b and continue manipulating b as an independent being, you need to:
a  = [1,2,3,4]
b = a.copy()
a.append(10)
print(b)

# Same is applied to the Dictionaries

a = {'first':1000, 'second':1500}
b = a 
a['third']= 10000
print(a)

a = {'first':100, 'second':1000}
b = a.copy() #b remained the same, with 2 keys and 2 values, while a is appended
a['third'] = 10000
print(b)

#Sets

    #In lists and tuples, order matters.
    #In dictionaries, keys matter while order is unimportant.
    #Sets are like dictionaries without keys, and order is unimportant.

my_set = {0,1,2} # example how order is not important in dictionaries
0 in my_set 

#Little about Set theory!
#1) Union "|" 
#2) intersection "&" (every element that is present in both set A and set B)
#3) set differencies "A - B" (every element that is in the set A but not in the set B)

a = {1,2}
b = {1,3}
a | b # 1 ,2 ,3 
a & b # 1
a - b #2

#check if a is subset of b

a = {1,2,3,4}
b = {7,4,3,2,1,0}
a.issubset(b) #Yes it is "True"
b.issubset(a) # False

In [134]:
#About Data Frames class (Pandas)

import pandas as pd
my_data = {'Name':['Maria','Anna','Sophia','Deborah'],
           'Height':[180, 167,152,177]}

print(my_data.keys())

print(my_data)
data=pd.DataFrame(my_data)
print(data)
data.loc[data['Height']>175]
#get height only of Sophia

Sophia_height = data.loc[data['Name']=="Sophia", 'Height']
display(data)
print(Sophia_height)

#how many [ROWS, COlUMNS]
data.shape #4 rows 2 columns
data.shape[0] #rows 
data.shape[1] #columns

dict_keys(['Name', 'Height'])
{'Name': ['Maria', 'Anna', 'Sophia', 'Deborah'], 'Height': [180, 167, 152, 177]}
      Name  Height
0    Maria     180
1     Anna     167
2   Sophia     152
3  Deborah     177

      Name  Height
0    Maria     180
1     Anna     167
2   Sophia     152
3  Deborah     177

2    152
Name: Height, dtype: int64

2